import { sql } from 'drizzle-orm'
import { timestamp, uuid } from 'drizzle-orm/pg-core'

// UUIDv7 generated by Postgres 18's native uuidv7(): time-sortable, does not leak counts.
export const id = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`)

export const createdAt = () =>
  timestamp('created_at', { withTimezone: true }).notNull().defaultNow()

export const updatedAt = () =>
  timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date())
