import { eq } from 'drizzle-orm'
import { afterAll, expect, test } from 'bun:test'
import { createDb, schema } from '../src'
import { migrateAll } from '../src/migrate-all'

const url = process.env.DATABASE_URL!
const { db, pool } = createDb(url)

afterAll(() => pool.end())

test('migrations are idempotent', async () => {
  await migrateAll(url)
  await migrateAll(url)
})

test('ids default to UUIDv7 generated by Postgres', async () => {
  const email = `schema-test-${crypto.randomUUID()}@example.com`
  const [row] = await db.insert(schema.user).values({ name: 'Schema test', email }).returning()
  await db.delete(schema.user).where(eq(schema.user.email, email))

  expect(row!.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/)
  expect(row!.role).toBe('user')
})

test('scan findings are unique per scan and Strix id, and cascade with the scan', async () => {
  const email = `scan-test-${crypto.randomUUID()}@example.com`
  const [owner] = await db.insert(schema.user).values({ name: 'Scan test', email }).returning()
  const [scan] = await db
    .insert(schema.scan)
    .values({ userId: owner!.id, targets: ['https://example.com/'], scanMode: 'quick' })
    .returning()
  expect(scan!.status).toBe('queued')
  expect(scan!.costUsd).toBe(0)
  expect(scan!.agents).toEqual([])

  const finding = {
    scanId: scan!.id,
    strixId: 'vuln-0001',
    title: 'XSS',
    severity: 'high' as const,
    foundAt: new Date(),
    report: { id: 'vuln-0001' },
  }
  await db.insert(schema.scanFinding).values(finding)
  const duplicate = db
    .insert(schema.scanFinding)
    .values(finding)
    .then(() => 'inserted')
    .catch(() => 'rejected')
  expect(await duplicate).toBe('rejected')

  await db.delete(schema.user).where(eq(schema.user.id, owner!.id))
  const left = await db
    .select()
    .from(schema.scanFinding)
    .where(eq(schema.scanFinding.scanId, scan!.id))
  expect(left).toHaveLength(0)
})
