import { eq } from 'drizzle-orm'
import { afterAll, expect, test } from 'bun:test'
import { createDb, schema } from '../src'
import { migrateAll } from '../src/migrate-all'

const url = process.env.DATABASE_URL!
const { db, pool } = createDb(url)

afterAll(() => pool.end())

test('migrations are idempotent', async () => {
  await migrateAll(url)
  await migrateAll(url)
})

test('ids default to UUIDv7 generated by Postgres', async () => {
  const email = `schema-test-${crypto.randomUUID()}@example.com`
  const [row] = await db.insert(schema.user).values({ name: 'Schema test', email }).returning()
  await db.delete(schema.user).where(eq(schema.user.email, email))

  expect(row!.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/)
  expect(row!.role).toBe('user')
})
